FROM python:3.11-slim-bullseye

ARG UID=11132
ARG GID=11133
ARG APP_DIR=/app

RUN addgroup --gid $GID llm-adm && adduser --uid $UID --ingroup llm-adm --disabled-password -q --gecos llm llm-apps
#RUN --mount=type=cache,target=/root/.cache/pip pip install -U pip

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    curl ffmpeg software-properties-common && \
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

#ENV CUDA_HOME=/usr/local/cuda
ENV PATH="/root/.cargo/bin:${PATH}"

WORKDIR $APP_DIR
RUN mkdir -p voices config

COPY requirements*.txt /app/

COPY *.py *.sh *.default.yaml README.md LICENSE /app/

ARG PRELOAD_MODEL
ENV PRELOAD_MODEL=${PRELOAD_MODEL}
ENV TTS_HOME=voices
ENV HF_HOME=voices
ENV COQUI_TOS_AGREED=1

RUN chown -R $UID:$GID $APP_DIR
USER $UID:$GID
RUN python -m venv $APP_DIR/.venv && . $APP_DIR/.venv/bin/activate && pip install  --no-cache-dir -r requirements.txt

CMD bash startup.sh
